# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainFrame.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import random
import string
from PyQt5 import QtCore, QtGui, QtWidgets
import winreg
import PyInstaller.__main__
import os, shutil, winshell,win32com.client
import subprocess


def foo(hive, flag):
    aReg = winreg.ConnectRegistry(None, hive)
    aKey = winreg.OpenKey(aReg, r"SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall",
                          0, winreg.KEY_READ | flag)

    count_subkey = winreg.QueryInfoKey(aKey)[0]

    software_list = []

    for i in range(count_subkey):
        software = {}
        try:
            asubkey_name = winreg.EnumKey(aKey, i)
            asubkey = winreg.OpenKey(aKey, asubkey_name)
            software['name'] = winreg.QueryValueEx(asubkey, "DisplayName")[0]

            try:
                software['version'] = winreg.QueryValueEx(asubkey, "DisplayVersion")[0]
            except EnvironmentError:
                software['version'] = 'undefined'
            try:
                software['publisher'] = winreg.QueryValueEx(asubkey, "Publisher")[0]
            except EnvironmentError:
                software['publisher'] = 'undefined'
            software_list.append(software)
        except EnvironmentError:
            continue

    return software_list





def createLauncher(apps,appName,iconFilePath):
    if len(appName) == 0 :
        # printing uppercase
        letters = string.ascii_uppercase
        appName = ''.join(random.choice(letters) for i in range(3))
        print(appName)
    # create .py file
    pyFileCreater(apps,appName)
    # createLauncherFile 
    createLauncherFile(appName,iconFilePath)

def createLauncherFile(appName,iconFilePath):
    temp = os.getcwd()
    if iconFilePath == "":
        PyInstaller.__main__.run([
        appName+'.py',
            '--onefile',
            '--clean',
        ])
    else:
        fileName = iconFilePath.split("/")
        iconFilePath = iconFilePath.replace("/","\\\\")
        shutil.copy2(iconFilePath,os.getcwd())
        PyInstaller.__main__.run([
        appName+'.py',
            '--onefile',
            '--clean',
            '-i'+str(fileName[len(fileName)-1]),
        ])
        os.remove(str(fileName[len(fileName)-1]))

    shutil.move(os.getcwd()+"\dist\\"+appName+".exe",os.getcwd()+"\\launchers")


    desktop = winshell.desktop()
    shell = win32com.client.Dispatch("WScript.Shell")
    target =  temp+"\\launchers\\"+appName+".exe" 
    icon =  temp+"\\launchers\\"+appName+".exe"
    path = os.path.join(desktop, appName+'.lnk')
    shortcut = shell.CreateShortCut(path)
    shortcut.Targetpath = target
    shortcut.IconLocation = icon
    shortcut.save()
    shutil.rmtree('build')
    shutil.rmtree('dist')
    os.remove(appName+'.py')
    os.remove(appName+'.spec')

def pyFileCreater(apps, appName):

    f = open(appName+".py", mode="wt")
    f.write("from AppOpener import open\n")

    for app in apps:
        f.write("open(\""+str(app)+"\")\n")
    f.close()




class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(550, 460, 141, 81))
        self.pushButton.setObjectName("pushButton")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 50, 451, 501))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_2.setGeometry(QtCore.QRect(480, 50, 301, 231))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(1)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_2.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)
        self.tableWidget_2.setRowCount(0)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 10, 161, 31))
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(570, 20, 111, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(590, 290, 101, 51))
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(490, 330, 281, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(490, 390, 281, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.iconFile = None

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

        self.iconFilePath = ""
    def browseFiles(self):
        text, placeholder = QtWidgets.QFileDialog.getOpenFileName(None,"Open File","C:\\","Images (*.ico)") 
        print(text)
        self.iconFilePath= text

    def loadPrograms(self):
            programs = foo(winreg.HKEY_LOCAL_MACHINE, winreg.KEY_WOW64_32KEY) + foo(winreg.HKEY_LOCAL_MACHINE, winreg.KEY_WOW64_64KEY) + foo(winreg.HKEY_CURRENT_USER, 0)
            row=0
            self.tableWidget.setRowCount(len(programs))
            for program in programs:
                self.tableWidget.setItem(row,0,QtWidgets.QTableWidgetItem(program['name']))
                row = row+1
    



    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "App Launcher"))
        self.pushButton.setText(_translate("mainWindow", "Create Launcher"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "Programs"))
        self.label.setText(_translate("mainWindow", "All Programs"))
        self.label_2.setText(_translate("mainWindow", "Apps to bundle"))
        self.label_3.setText(_translate("mainWindow", "Name of Launcher"))
        self.pushButton_2.setText(_translate("mainWindow", "icon"))

        def addProgram():
            count = self.tableWidget_2.rowCount()
            self.tableWidget_2.setRowCount(count+1)
            self.tableWidget_2.setItem(count,0,QtWidgets.QTableWidgetItem(self.tableWidget.currentItem().text()))

        def removeProgram():
            self.tableWidget_2.removeRow(self.tableWidget_2.currentRow())

        def removeAllPrograms():
            rowCount = self.tableWidget_2.rowCount()
            for i in range(rowCount):
                curRow = self.tableWidget_2.rowAt(i)
                self.tableWidget_2.removeRow(curRow)

        def loadAppsTOCL():
            apps = []
            count = self.tableWidget_2.rowCount()
            for i in range(count):
                apps.append(self.tableWidget_2.item(i,0).text())
            createLauncher(apps,self.lineEdit.text(),self.iconFilePath)
            self.lineEdit.clear()
            self.iconFilePath=""
            removeAllPrograms()
        self.loadPrograms()
    
        self.tableWidget.clicked.connect(addProgram)
        self.tableWidget_2.clicked.connect(removeProgram)
        self.pushButton_2.clicked.connect(self.browseFiles)
        self.pushButton.clicked.connect(loadAppsTOCL)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())









